Algoritmo "18"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 29/03/2018
Var
// Seção de Declarações das variáveis 
n:real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
leia(n);
se ( n > 20 ) e ( n < 90 ) então
escreval(n,"está compreendido entre 20 e 90!");
senão
escreval(n,"não está compreendido entre 20 e 90!");
fimse

Fimalgoritmo