Algoritmo "2"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 29/03/2018
Var
// Seção de Declarações das variáveis 
a,b,soma:real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval ("digite o primeiro numero")
leia(a)
escreval ("digite o segundo numero")
leia(b)
soma <- a + b;
se ( soma > 10 ) então
escreval (soma);
fimse
Fimalgoritmo