Algoritmo "4"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 29/03/2018
Var
// Seção de Declarações das variáveis 
n:real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
leia(n);
se ( n > 0 ) então
escreval(n," é POSITIVO");
senão
se ( n < 0 ) então
escreval(n,"é NEGATIVO");
senão
escreval(n,"é NULO");
fimse
fimse
Fimalgoritmo