Algoritmo "5"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 29/03/2018
Var
// Seção de Declarações das variáveis 
n1,n2,soma:real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
leia(n1,n2)
soma <- n1+n2
se ( soma > 20 ) então
escreval("Soma: ", soma + 8)
senão
escreval("Soma: ", soma – 5)
fimse
Fimalgoritmo