Algoritmo "semnome"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 29/03/2018
Var
// Seção de Declarações das variáveis 
n:real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite um numero:");
leia(n)
se ( n >= 0 ) então
escreval("Raiz quadrada:", raiz(n))
senão
escreval("Quadrado: ",n**2)
fimse
Fimalgoritmo