Algoritmo "7"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 29/03/2018
Var
// Seção de Declarações das variáveis 
n,resto:real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
leia(n)
resto <- n mod 3
se ( resto = 0 ) então
escreval("é múltiplo de 3”);
senão
escreval("não é múltiplo de 3");
fimse
Fimalgoritmo