Algoritmo "8"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 29/03/2018
Var
// Seção de Declarações das variáveis 
n,resto:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
leia(n)
resto <- n mod 5;
se ( resto = 0 ) então
escreval("é divisível por 5");
senão
escreval("não é divisível por 5");
fimse

Fimalgoritmo