Algoritmo "semnome"
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 21/06/2018
// a soma de um numero com o numero anterior (10+9) = 19
Var
i, num, total : inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval ("Digite um numero para calcular a tabuada do mesmo:")
leia (num)
para i de 1 ate 10 passo 1 faca
total <- i*num
escreval (i," x",num," =",total)
fimpara
Fimalgoritmo